# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: http-https-echo

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: http-echo
    main: .
    binary: http-echo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

kos:
  - id: ko-build
    build: http-echo
    base_image: cgr.dev/chainguard/static:latest
    repositories:
      - ghcr.io/tamcore/http-https-echo
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
